site_name: VT Help Docs
pages:
- VT Help Docs - Home: index.md
- Courseware Management: courseware_mgmt/overview.md
- VT2GO: vt2go/overview.md
- Content Containers: content_containers/overview.md
- Content Roles: content_roles/overview.md
- Access Levels: access_levels/overview.md
- Activating/Deactivating Content: turning_on-off_content/overview.md
- System Settings: system_settings/overview.md
- Location Settings: location_settings/overview.md
- Theme Settings: theme_settings/overview.md
- Certifications: certifications/overview.md
- The Impersonate Feature: impersonate/overview.md
- Tutorials: getting_started/overview.md
- Super Users: superusers/overview.md
- Webservices: webservices/overview.md

theme: readthedocs
